[workspace]
resolver = "2"

members = [
	"fusion-api",
	"fusion-config",
	"fusion-state",
	"fusion-sequencer",
	"fusion-types",
]

default-members = ["fusion-sequencer"]

exclude = [ "fusion-powdr-verifier" ]
