circuit_path = "../circuits/out"
circuit_abi_path = "../circuits/abi.json"
proving_key_path = "../circuits/proving.key"
database_path = "./db"
eth_rpc_url = "http://localhost:8545"
eth_private_key = "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
min_tx_block = 1
socket_address = "127.0.0.1"
socket_port = 38171
fusion_l1_contract = "0x5fbdb2315678afecb367f032d93f642f64180aa3"
