[package]
name = "trollup-config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "1.0.2"
serde = "1.0.152"
serde_json = "1.0.91"
toml = "0.6.0"
