name: Rust

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: ⚡ Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
    - name: Compile circuit
      run: cd circuits && zokrates compile -i fusion.zok
    - name: Compute trusted setup
      run: cd circuits && zokrates setup
    - name: Set up nightly
      run: rustup default nightly-2023-01-03
    - name: Install dependencies
      run: rustup component add clippy rustfmt
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
    - name: Lint
      run: cargo clippy --all --all-features -- -D warnings
    - name: Format
      run: cargo fmt --check --verbose
