name: Rust

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: ⚡ Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
    - name: Set up nightly
      run: rustup default nightly
    - name: Install dependencies
      run: rustup component add clippy rustfmt
    - name: Build sequencer
      run: cd sequencer && cargo build --verbose
    - name: Run sequencer tests
      run: cd sequencer && cargo test --verbose
    - name: Lint
      run: cd sequencer && cargo clippy --all --all-features -- -D warnings
    - name: Format
      run: cd sequencer && cargo fmt --check --verbose
