name: Fusion build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_circuit:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: ⚡ Cache Circuits
        id: cache-circuits
        uses: actions/cache@v3
        with:
          path: circuits/
          key: cache-circuits-${{ hashFiles('**/out') }}
      - name: Compile circuit
        if: steps.cache-circuits.outputs.cache-hit != 'true'
        run: cd circuits && zokrates compile -i fusion.zok
      - name: Compute trusted setup
        if: steps.cache-circuits.outputs.cache-hit != 'true'
        run: cd circuits && zokrates setup

  build:
    needs: build_circuit
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: ⚡ Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Set up Rust nightly
        run: rustup default nightly-2023-01-03
      - name: Install dependencies
        run: rustup component add clippy rustfmt
      - name: Restore cached circuits
        id: cache-circuits
        uses: actions/cache/restore@v3
        with:
          path: circuits/
          key: cache-circuits-${{ hashFiles('**/out') }}
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
      - name: Lint
        run: cargo clippy --all --all-features -- -D warnings
      - name: Format
        run: cargo fmt --check --verbose
